### PR TITLE
responsive profile settings tabs

### PR DESCRIPTION
**Pull request by myniqx**
https://github.com/freedomcombination/monorepo/issues/1402

and also there are 403 errors. for example, while upload avatar in production.

### CODE REVIEW

**Comment by MustafaTRKYLMZ** [comment]
I couldn't change my password in production. Is it an error or later we will look it?

**Comment by myniqx** [comment]
> I couldn't change my password in production. Is it an error or later we will look it?

Thats because some permissions havent added to roles..

**Review by 7alip — APPROVED** [review]
Thanks, I tweaked the design a bit

**Comment by 7alip** [comment]
@myniqx You can also add `inMailingList`, `availableHours` fields. You can also refactor Details tab by using hook form and FormItem components if you want. Or just merge it

**Pull request merged**
