### PR TITLE
mailchimp

### PR DESCRIPTION
**Pull request by burakndrlnd**
i couldnt test it.
it needed mailchimp payed account. i hope it works :)

what it does:
on 'afterCreate' course, creates mailchimp list with courses 'title_en'

on 'afterCreate' application-course, add applicant' mail adress to course's mailchimp's list

and there is a button if course without mailchimp it creates mail list and adds all applications' mails to its list or there is a list, simply redirect you to mailchimp's dashboard
of course, its in teory :)

### CODE REVIEW

**Comment by 7alip** [comment]
@MustafaTRKYLMZ Do we have paid mailchimp account?

Variables: `MAILCHIMP_API_KEY` and `MAILCHIMP_API_SERVER`

**Comment by MustafaTRKYLMZ** [comment]
> @MustafaTRKYLMZ Do we have paid mailchimp account?
> 
> Variables: `MAILCHIMP_API_KEY` and `MAILCHIMP_API_SERVER`

I know, We don't have it. We have to buy it.

**Comment by MustafaTRKYLMZ** [comment]
> > @MustafaTRKYLMZ Do we have paid mailchimp account?
> > Variables: `MAILCHIMP_API_KEY` and `MAILCHIMP_API_SERVER`
> 
> I know, We don't have it. We have to buy it.

Is it not posssible with free account for test?

**Comment by burakndrlnd** [comment]
> > > @MustafaTRKYLMZ Do we have paid mailchimp account?
> > > Variables: `MAILCHIMP_API_KEY` and `MAILCHIMP_API_SERVER`
> > 
> > 
> > I know, We don't have it. We have to buy it.
> 
> Is it not posssible with free account for test?

i tried. but whenever i tried my request denied. but let me try one more thing.

**Comment by burakndrlnd** [comment]
sorry, no luck here. first i already tested it and failed. but first example of the docs worked (simple ping to mailchimp server). as it seems some of the apis need authorization

> https://mailchimp.com/developer/marketing/docs/errors/ 
Authorization Failure: User does not have access to the requested operation
Your account’s pricing plan may not permit access to a feature; upgrading the account’s plan may fix these errors.

**Pull request closed without merging**
