### PR TITLE
Burak localized component

### PR DESCRIPTION
**Pull request by myniqx**
image

check localhost:3000/test-edit-modal

### CODE REVIEW

**Comment by myniqx** [comment]
@7alip 
-i added all locaized komponent into field component with error message support.
-now translate button get disabled if content empty
-i add some shadow because i cant see boundaries between fields. ( i ll revert this when issue is done )

* still cant see default values in localized komponent.

end of the day.

**Comment by myniqx** [comment]
image

**Comment by myniqx** [comment]
http://localhost:3000/test-model-edit
@7alip looks good.

**Comment by myniqx** [comment]
image
what is on that image:
create button now in [endpoint].tsx and its work on category (i didnt have time to test others)
added slugfield which can sync to another field or editable manually.
both create and edit modal using localizedfield and dynamicfield so far does the job.

i have some other stuff to fix/add. didnt finish yet.
but end of the day...
@7alip

**Comment by 7alip** [comment]
@myniqx 

- Added some small fixes. 
- Showing global create button only on homepage. 

**Some small issues I noticed:**

- In course create, I can select max 2 languages at once
- Translate to language dropdown menu disappears when hovering on the items

Screenshot 2024-11-19 at 07 32 15

**Comment by myniqx** [comment]
some issues :
image

**Comment by myniqx** [comment]
@7alip  can you review ?

**Comment by myniqx** [comment]
image
dafult values are now visible

**Pull request merged**
